on: 
  schedule: 
    - cron:  '0 0 1 * *' # every first day of the month at 00:00
jobs:
  build:
    runs-on: ubuntu-latest
    name: Calenda
    steps:
      - name: curl calenda
        run: curl calenda.it
